apiVersion: 1.0.0
kind: Plugin
metadata:
  name: CoAP Gateway
  description: CoAP Gateway Plugin for the Reekoh IoT Platform
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - gateway
    - coap

  loadBalancing:
    method: http
    enableSticky: true

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      dataUrl:
        label: Data Url
        type: String
        maxLength: 1000
        required: false
        default: /reekoh/data
        help: "(Optional) The url to listen to for device data. Default: /reekoh/data."
        maxLength: 1000
      commandUrl:
        label: Command Url
        type: String
        maxLength: 1000
        required: false
        default: /reekoh/commands
        help: "(Optional) The url to listen to for device messages or commands. Default: /reekoh/commands."
        maxLength: 1000